#!/usr/bin/env bash
# coding-agent 一键安装脚本
#
# 两种用法：
#
#   A) 远程一行装（无需先 clone）：
#        curl -fsSL https://raw.githubusercontent.com/alloevil/coding-agent/master/install.sh | bash
#      脚本会自动 git clone 到 ./coding-agent 再安装。
#
#   B) 已 clone 后本地装：
#        ./install.sh
#
# 选项：
#   --with-tokenizer  额外装 tiktoken（更准的 token 计数）
#   --with-browser    额外装 playwright（browser_* 工具）
#   --no-tui          跳过构建 Rust 全屏 TUI（默认构建，需 cargo）
#   --all             装上面所有可选依赖（TUI 默认已构建）
#   --no-dev          不装 dev 依赖（仅运行所需）
#   --dir <path>      clone 的目标目录（默认 ./coding-agent）
#
# 安装到独立的 .venv，避免污染全局 / conda 环境（coding-agent 固定了
# httpx>=0.27、rich 等版本，装进共享环境可能与其它项目冲突）。
set -euo pipefail

REPO_URL="https://github.com/alloevil/coding-agent.git"
CLONE_DIR="coding-agent"
VENV=".venv"
WITH_TOKENIZER=0
WITH_BROWSER=0
WITH_TUI=1
DEV=1

# 解析参数（先解析 --dir，clone 时要用）
args=("$@")
i=0
while [ $i -lt ${#args[@]} ]; do
  case "${args[$i]}" in
    --with-tokenizer) WITH_TOKENIZER=1 ;;
    --with-browser)   WITH_BROWSER=1 ;;
    --with-tui)       WITH_TUI=1 ;;
    --no-tui)         WITH_TUI=0 ;;
    --all)            WITH_TOKENIZER=1; WITH_BROWSER=1; WITH_TUI=1 ;;
    --no-dev)         DEV=0 ;;
    --dir)            i=$((i+1)); CLONE_DIR="${args[$i]}" ;;
    -h|--help)
      sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown option: ${args[$i]} (try --help)"; exit 1 ;;
  esac
  i=$((i+1))
done

# 定位仓库根：
#   - 如果脚本所在目录就是仓库（有 pyproject.toml）→ 用它（本地用法 B）
#   - 否则（如 curl | bash，无脚本文件）→ git clone 后进入（远程用法 A）
SCRIPT_DIR=""
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/pyproject.toml" ]; then
  cd "$SCRIPT_DIR"
else
  # 远程安装：需要 git
  if ! command -v git >/dev/null 2>&1; then
    echo "❌ git not found. Install git, or clone the repo manually then run ./install.sh"
    exit 1
  fi
  if [ -d "$CLONE_DIR/.git" ]; then
    echo "📁 Found existing clone at $CLONE_DIR, updating ..."
    git -C "$CLONE_DIR" pull --ff-only || true
  else
    echo "⬇️  Cloning $REPO_URL → $CLONE_DIR ..."
    git clone --depth 1 "$REPO_URL" "$CLONE_DIR"
  fi
  cd "$CLONE_DIR"
fi

# 1. 检查 python3
if ! command -v python3 >/dev/null 2>&1; then
  echo "❌ python3 not found. Please install Python 3.10+ first."
  exit 1
fi
PYV=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
echo "🐍 Using python3 ($PYV)"

# 2. 创建 venv
if [ ! -d "$VENV" ]; then
  echo "📦 Creating virtualenv at $VENV ..."
  python3 -m venv "$VENV"
else
  echo "📦 Reusing existing virtualenv at $VENV"
fi

PIP="$VENV/bin/pip"
"$PIP" install -q --upgrade pip

# 3. 组装 extras
EXTRAS=""
if [ "$DEV" = "1" ]; then EXTRAS="dev"; fi
if [ "$WITH_TOKENIZER" = "1" ]; then EXTRAS="${EXTRAS:+$EXTRAS,}tokenizer"; fi
if [ "$WITH_BROWSER" = "1" ]; then EXTRAS="${EXTRAS:+$EXTRAS,}browser"; fi

if [ -n "$EXTRAS" ]; then
  echo "⬇️  Installing coding-agent with extras: [$EXTRAS] ..."
  "$PIP" install -q -e ".[$EXTRAS]"
else
  echo "⬇️  Installing coding-agent ..."
  "$PIP" install -q -e .
fi

# 4. playwright 浏览器二进制（如装了 browser extra）
if [ "$WITH_BROWSER" = "1" ]; then
  echo "🌐 Installing Playwright browser (chromium) ..."
  "$VENV/bin/python" -m playwright install chromium || \
    echo "⚠️  playwright browser install failed; browser_* tools may not work."
fi

# 5. Rust 全屏 TUI（默认构建；需要 cargo 工具链，--no-tui 可跳过）
TUI_BIN=""
if [ "$WITH_TUI" = "1" ]; then
  if command -v cargo >/dev/null 2>&1; then
    echo "🦀 Building the Rust TUI (cargo build --release) ..."
    if (cd tui && cargo build --release 2>/dev/null); then
      TUI_BIN="tui/target/release/coding-agent-tui"
      echo "   Built $TUI_BIN"
    else
      echo "⚠️  Rust TUI build failed; the CLI and rich --tui still work."
    fi
  else
    echo "ℹ️  cargo not found — skipping the full-screen Rust TUI."
    echo "    Install Rust (https://rustup.rs) and re-run for it; the CLI and"
    echo "    the built-in rich --tui work without it."
  fi
fi

# 6. 安装 PATH 启动器（~/.local/bin/coding-agent）——一个命令即可启动，
#    自动选 Rust TUI（若已构建）否则 CLI，并注入正确的 python/dir。
INSTALL_DIR="$(pwd)"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/coding-agent"
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# coding-agent launcher (generated by install.sh) — do not edit by hand.
export CODING_AGENT_PYTHON="$INSTALL_DIR/.venv/bin/python"
export CODING_AGENT_DIR="$INSTALL_DIR"
TUI="$INSTALL_DIR/tui/target/release/coding-agent-tui"
# --setup / --tui / other flags pass through. Rust TUI is default when built.
if [ -x "\$TUI" ] && [ "\${1:-}" != "--cli" ]; then
  exec "\$TUI" "\$@"
else
  [ "\${1:-}" = "--cli" ] && shift
  exec "$INSTALL_DIR/.venv/bin/coding-agent" "\$@"
fi
LAUNCHER_EOF
chmod +x "$LAUNCHER"

echo ""
echo "✅ Installed. Run:  coding-agent"
echo "   First launch walks you through setup (provider, API key, model) —"
echo "   no environment variables needed."
echo ""
# PATH 检查：~/.local/bin 不在 PATH 时给一行提示
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;  # 已在 PATH
  *)
    echo "   ⚠️  $BIN_DIR is not on your PATH. Add this to your shell rc:"
    echo "         export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo "       (or run directly: $LAUNCHER)"
    echo ""
    ;;
esac
echo "   Reconfigure anytime:  coding-agent --setup"
if [ -z "$TUI_BIN" ]; then
  echo "   (install Rust — https://rustup.rs — then re-run for the full-screen TUI)"
fi
