"""
项目记忆管理器 - 跨会话项目级记忆系统

管理 .agent/ 目录下的项目知识：
- PROJECT.md: 人类可读的项目知识
- knowledge.jsonl: 结构化知识条目
- sessions/: 历史会话摘要

灵感来源：Claude Code 的 CLAUDE.md 设计
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any


# 项目 agent 元数据目录名
AGENT_DIR = ".agent"

# 默认相似度阈值（内容哈希前缀长度）
SIMILARITY_PREFIX_LEN = 32


@dataclass
class KnowledgeEntry:
    """单条知识条目"""
    content: str
    tags: list[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)
    source: str = ""  # 来自哪个会话
    id: str = ""  # 内容哈希，用于去重

    def __post_init__(self) -> None:
        if not self.id:
            self.id = self._compute_id()

    def _compute_id(self) -> str:
        """基于内容生成唯一 ID（用于去重）"""
        normalized = self.content.strip().lower()
        return hashlib.sha256(normalized.encode()).hexdigest()[:16]

    def to_dict(self) -> dict[str, Any]:
        """转换为字典（用于 JSON 序列化）"""
        return {
            "id": self.id,
            "content": self.content,
            "tags": self.tags,
            "timestamp": self.timestamp,
            "source": self.source,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> KnowledgeEntry:
        """从字典创建"""
        return cls(
            content=data["content"],
            tags=data.get("tags", []),
            timestamp=data.get("timestamp", 0),
            source=data.get("source", ""),
            id=data.get("id", ""),
        )

    def matches_query(self, query: str) -> bool:
        """检查是否匹配搜索查询（关键词）"""
        query_lower = query.lower()
        # 搜索内容和标签
        if query_lower in self.content.lower():
            return True
        return any(query_lower in tag.lower() for tag in self.tags)

    def matches_tags(self, tags: list[str]) -> bool:
        """检查是否包含所有指定标签"""
        entry_tags = {t.lower() for t in self.tags}
        return all(t.lower() in entry_tags for t in tags)


DEFAULT_PROJECT_MD_TEMPLATE = """# Project: {project_name}

> Auto-generated by coding-agent memory system. Edit freely.

## Description

<!-- What does this project do? -->

## Tech Stack

<!-- Languages, frameworks, key dependencies -->

## Code Conventions

<!-- Style guide, naming conventions, patterns -->

## Common Commands

```bash
# Build
# Test
# Lint
# Run
```

## Known Issues

<!-- Document gotchas, workarounds, tech debt -->

## Notes

<!-- Anything else useful for future sessions -->
"""


class ProjectMemoryManager:
    """
    项目级记忆管理器

    每个项目目录下维护 .agent/ 目录，存储：
    - PROJECT.md: 人类可读的项目知识
    - knowledge.jsonl: 结构化知识条目
    - sessions/: 历史会话摘要

    用法：
        manager = ProjectMemoryManager("/path/to/project")
        manager.init_project("My Project")
        manager.save_knowledge(content="...", tags=["python", "api"])
        results = manager.search_knowledge(query="api")
    """

    def __init__(self, project_root: str | Path) -> None:
        self.project_root = Path(project_root).resolve()
        self.agent_dir = self.project_root / AGENT_DIR
        self.project_md = self.agent_dir / "PROJECT.md"
        self.knowledge_file = self.agent_dir / "knowledge.jsonl"
        self.sessions_dir = self.agent_dir / "sessions"

    @property
    def is_initialized(self) -> bool:
        """项目是否已初始化（.agent/ 目录是否存在）"""
        return self.agent_dir.is_dir() and self.project_md.exists()

    def init_project(self, project_name: str | None = None) -> Path:
        """
        初始化项目记忆目录

        如果 .agent/ 已存在则跳过 PROJECT.md 创建（不覆盖用户编辑）。

        Args:
            project_name: 项目名称，默认取目录名

        Returns:
            .agent/ 目录路径
        """
        self.agent_dir.mkdir(parents=True, exist_ok=True)
        self.sessions_dir.mkdir(parents=True, exist_ok=True)

        # 仅在 PROJECT.md 不存在时创建
        if not self.project_md.exists():
            name = project_name or self.project_root.name
            self.project_md.write_text(
                DEFAULT_PROJECT_MD_TEMPLATE.format(project_name=name),
                encoding="utf-8",
            )

        # 确保 knowledge.jsonl 存在
        if not self.knowledge_file.exists():
            self.knowledge_file.touch()

        return self.agent_dir

    def read_project_md(self) -> str:
        """读取 PROJECT.md 内容"""
        if not self.project_md.exists():
            return ""
        return self.project_md.read_text(encoding="utf-8")

    def write_project_md(self, content: str) -> None:
        """写入 PROJECT.md 内容"""
        self.agent_dir.mkdir(parents=True, exist_ok=True)
        self.project_md.write_text(content, encoding="utf-8")

    def load_knowledge(self) -> list[KnowledgeEntry]:
        """加载所有知识条目"""
        entries: list[KnowledgeEntry] = []
        if not self.knowledge_file.exists():
            return entries

        for line_num, line in enumerate(
            self.knowledge_file.read_text(encoding="utf-8").splitlines(), 1
        ):
            line = line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)
                entries.append(KnowledgeEntry.from_dict(data))
            except (json.JSONDecodeError, KeyError):
                # 跳过损坏的行
                continue

        return entries

    def save_knowledge(
        self,
        content: str,
        tags: list[str] | None = None,
        source: str = "",
    ) -> KnowledgeEntry:
        """
        保存一条知识条目

        自动去重：如果内容（忽略大小写和首尾空白）已存在则跳过。

        Args:
            content: 知识内容
            tags: 标签列表
            source: 来源会话标识

        Returns:
            保存的条目（如果是重复的则返回已有条目）
        """
        entry = KnowledgeEntry(
            content=content,
            tags=tags or [],
            source=source,
        )

        # 去重检查
        existing = self.load_knowledge()
        existing_ids = {e.id for e in existing}
        if entry.id in existing_ids:
            return entry  # 已存在，跳过

        # 追加写入
        self.agent_dir.mkdir(parents=True, exist_ok=True)
        with open(self.knowledge_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry.to_dict(), ensure_ascii=False) + "\n")

        return entry

    def search_knowledge(
        self,
        query: str = "",
        tags: list[str] | None = None,
        limit: int = 10,
    ) -> list[KnowledgeEntry]:
        """
        搜索知识条目

        支持关键词搜索（匹配内容）和标签过滤。
        query 和 tags 之间是 AND 关系。

        Args:
            query: 搜索关键词（匹配内容和标签）
            tags: 标签过滤（必须全部匹配）
            limit: 最大返回数量

        Returns:
            匹配的知识条目列表
        """
        entries = self.load_knowledge()
        results: list[KnowledgeEntry] = []

        for entry in entries:
            # 标签过滤
            if tags and not entry.matches_tags(tags):
                continue
            # 关键词搜索
            if query and not entry.matches_query(query):
                continue
            results.append(entry)
            if len(results) >= limit:
                break

        return results

    def save_session_summary(
        self,
        session_id: str,
        summary: str,
        metadata: dict[str, Any] | None = None,
    ) -> Path:
        """
        保存会话摘要

        Args:
            session_id: 会话 ID
            summary: 摘要文本
            metadata: 附加元数据

        Returns:
            摘要文件路径
        """
        self.sessions_dir.mkdir(parents=True, exist_ok=True)
        session_file = self.sessions_dir / f"{session_id}.json"

        data = {
            "session_id": session_id,
            "summary": summary,
            "timestamp": time.time(),
            "metadata": metadata or {},
        }

        session_file.write_text(
            json.dumps(data, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        return session_file

    def list_session_summaries(self, limit: int = 20) -> list[dict[str, Any]]:
        """列出最近的会话摘要"""
        if not self.sessions_dir.exists():
            return []

        files = sorted(
            self.sessions_dir.glob("*.json"),
            key=lambda f: f.stat().st_mtime,
            reverse=True,
        )

        summaries = []
        for f in files[:limit]:
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                summaries.append(data)
            except (json.JSONDecodeError, OSError):
                continue

        return summaries

    def get_context_for_agent(self) -> str:
        """
        获取供 Agent 启动时注入的项目上下文

        返回 PROJECT.md 内容 + 最近的知识摘要，
        作为 system prompt 的一部分注入。

        Returns:
            格式化的项目上下文字符串
        """
        parts: list[str] = []

        # PROJECT.md
        project_md = self.read_project_md()
        if project_md:
            parts.append("## Project Memory (PROJECT.md)\n\n" + project_md)

        # 最近的知识条目（取最新的 10 条）
        recent = self.load_knowledge()
        if recent:
            # 按时间倒序，取前 10
            recent.sort(key=lambda e: e.timestamp, reverse=True)
            recent = recent[:10]
            knowledge_lines = ["## Recent Project Knowledge\n"]
            for entry in recent:
                tag_str = f" [{', '.join(entry.tags)}]" if entry.tags else ""
                knowledge_lines.append(f"- {entry.content}{tag_str}")
            parts.append("\n".join(knowledge_lines))

        return "\n\n".join(parts) if parts else ""
